import { resourceAddress, type AgentformIR } from '@agentform/ir';
import type {
  CompatibilityReport,
  FeatureSupportEntry,
  FeatureSupportLevel,
} from '@agentform/plugin-sdk';
import {
  AUTOGEN_AGENTCHAT_VERSION,
  AUTOGEN_EXT_VERSION,
  PYTHON_VERSION_REQUIREMENT,
} from './versions.js';

/**
 * Workflow node types this adapter can generate, and at what fidelity.
 * `agent` maps directly to a `RoundRobinGroupChat` participant (or the sole
 * agent, if there's only one). `terminate` needs no participant of its own
 * — it just marks where the conversation is expected to end. `humanApproval`
 * maps to a real `UserProxyAgent` participant (§13.5 "User proxy
 * abstractions where safe") — a genuine AutoGen construct, but a
 * general-purpose "human participant in the conversation" primitive being
 * repurposed to emulate an approval *gate* specifically, which AutoGen has
 * no purpose-built name for (unlike LangGraph's `interrupt()`) — hence
 * `emulated`, not `supported`, matching Phase 9's own illustrative
 * compatibility table's "Human approval: AutoGen: emulated" entry.
 * `tool`/`router`/`loop`/`parallel`/etc. have no generator: AutoGen's Team
 * model has no explicit node graph (it's driven by participants +
 * termination conditions, not declared edges), so there's no faithful
 * representation for an explicit branching/looping workflow node — see
 * §13.5's "Do not generate unrestricted code execution by default" and
 * this codebase's "no expression evaluator for `when` conditions" scope
 * limit (same reasoning as every other adapter's router/loop nodes).
 */
const NODE_TYPE_LEVELS: Readonly<Record<string, FeatureSupportLevel>> = {
  agent: 'supported',
  humanApproval: 'emulated',
  terminate: 'supported',
};

const SUPPORTED_TOOL_TYPES = new Set([
  'function',
  'http',
  'openapi',
  'mcp',
  'database',
  'queue',
  'agent',
  'humanApproval',
  'customPlugin',
]);

export function validateAutoGenCompatibility(ir: AgentformIR): CompatibilityReport {
  const entries: FeatureSupportEntry[] = [];

  for (const [id, tool] of ir.tools) {
    const address = resourceAddress('tool', id);
    if (SUPPORTED_TOOL_TYPES.has(tool.type)) {
      entries.push({
        feature: `tool (${tool.type})`,
        level: 'supported',
        resourceAddress: address,
      });
    } else {
      entries.push({
        feature: `tool (${tool.type})`,
        level: 'unsupported',
        detail: `tool type "${tool.type}" has no AutoGen function-tool equivalent yet`,
        resourceAddress: address,
      });
    }
  }

  for (const [workflowId, workflow] of ir.workflows) {
    for (const [nodeId, node] of workflow.nodes) {
      const address = `${resourceAddress('workflow', workflowId)}.nodes.${nodeId}`;
      const level = NODE_TYPE_LEVELS[node.type];
      if (level) {
        const detail =
          node.type === 'humanApproval'
            ? "maps to a UserProxyAgent participant — a real construct repurposed to emulate an approval gate, not AutoGen's own purpose-built primitive"
            : undefined;
        entries.push({
          feature: `workflow node (${node.type})`,
          level,
          resourceAddress: address,
          detail,
        });
      } else {
        entries.push({
          feature: `workflow node (${node.type})`,
          level: 'unsupported',
          detail: `"${node.type}" nodes have no generator in this adapter yet — AutoGen's Team model has no explicit node graph`,
          resourceAddress: address,
        });
      }
    }
  }

  return {
    target: 'autogen',
    entries,
    generatedDependencies: {
      'autogen-agentchat': AUTOGEN_AGENTCHAT_VERSION,
      'autogen-ext': AUTOGEN_EXT_VERSION,
    },
    frameworkVersion: AUTOGEN_AGENTCHAT_VERSION,
    runtimeRequirements: [`python ${PYTHON_VERSION_REQUIREMENT}`],
    securityWarnings: [
      'Generated code never embeds API keys — set them via environment variables; see .env.example.',
      'No code-execution tool or executor is generated by default (§13.5 "Do not generate unrestricted code execution by default") — only what the specification explicitly declares.',
    ],
    hasBlockingIncompatibility: entries.some((entry) => entry.level === 'unsupported'),
  };
}
