import { toIdentifier } from '@agentform/compiler';
import type { AgentformIR } from '@agentform/ir';
import {
  AUTOGEN_AGENTCHAT_VERSION,
  AUTOGEN_EXT_VERSION,
  PYTHON_VERSION_REQUIREMENT,
} from './versions.js';

/**
 * A real, installable `pyproject.toml` — same verified `hatchling` +
 * `packages = ["src"]` pattern as `@agentform/adapter-langgraph` (real
 * `pip install .` confirmed there against the identical `src`-named-package
 * layout). Pins `autogen-ext[openai]` specifically: the `openai` extra is
 * what makes `autogen_ext.models.openai` importable, the most common
 * starting point referenced in the generated model-client stub's docstring
 * — a real provider may need a different extra (`anthropic`, `azure`,
 * `ollama`, ...), left for the user to adjust once they fill in the stub.
 */
export function generatePyprojectToml(ir: AgentformIR): string {
  return [
    '[project]',
    `name = ${JSON.stringify(ir.application.name)}`,
    `version = ${JSON.stringify(ir.application.version)}`,
    `requires-python = ${JSON.stringify(PYTHON_VERSION_REQUIREMENT)}`,
    'dependencies = [',
    `    ${JSON.stringify(`autogen-agentchat==${AUTOGEN_AGENTCHAT_VERSION}`)},`,
    `    ${JSON.stringify(`autogen-ext[openai]==${AUTOGEN_EXT_VERSION}`)},`,
    ']',
    '',
    '[build-system]',
    'requires = ["hatchling"]',
    'build-backend = "hatchling.build"',
    '',
    '[tool.hatch.build.targets.wheel]',
    'packages = ["src"]',
    '',
  ].join('\n');
}

/** Same reasoning as every other Python adapter: `model.provider` is free-form, so there's no single fixed credential env var to name without guessing — this documents the declared models as a starting point instead. */
export function generateEnvExample(ir: AgentformIR): string {
  const lines = [
    '# Agent model clients are generated as stubs (see src/models/) — wire up',
    'your model provider(s) of choice and set their credentials here. Nothing',
    'in generated code reads these automatically; this file is a starting point.',
  ].map((line) => `# ${line}`);
  const modelLines = [...ir.models.entries()].map(
    ([id, model]) => `# ${id}: provider=${model.provider} model=${model.model}`,
  );
  return [...lines, '#', ...modelLines, ''].join('\n');
}

export function generateReadme(ir: AgentformIR): string {
  return [
    `# ${ir.application.name} (AutoGen)`,
    '',
    'Generated by [Agentform](https://github.com/YASSERRMD/AgentForm) — do not edit the files under `src/` by hand; re-run `agentform compile --target autogen` instead.',
    '',
    '## Setup',
    '',
    '```bash',
    `python3 -m venv .venv && source .venv/bin/activate  # requires Python ${PYTHON_VERSION_REQUIREMENT}`,
    `pip install "autogen-agentchat==${AUTOGEN_AGENTCHAT_VERSION}" "autogen-ext[openai]==${AUTOGEN_EXT_VERSION}"`,
    'cp .env.example .env   # then fill in your model provider credentials',
    '```',
    '',
    '## Run',
    '',
    '```bash',
    'python -m src.main',
    '```',
    '',
    '`pip install .` also works (see `pyproject.toml`) if you prefer an installed package over running from the project root.',
    '',
    '## Human approval',
    '',
    'Nodes generated from `humanApproval` workflow nodes become `UserProxyAgent`',
    'participants — a real AutoGen construct repurposed to pause the',
    'conversation for a human response, since AutoGen has no purpose-built',
    '"approval gate" primitive the way some other frameworks do. Its',
    '`input_func` is a stub; wire it to a real input source (a console prompt,',
    'a Slack message, a web callback, ...).',
    '',
    '## Test',
    '',
    'This project has no generated tests — add your own and wire up a test runner of your choice (e.g. `pytest`).',
    '',
    '## Security',
    '',
    '- Agent model clients and tool bodies are generated as `NotImplementedError` stubs; nothing runs until you implement them.',
    '- No code-execution tool or executor is generated by default — only what the specification explicitly declares.',
    '- No credentials are embedded in generated code — see `.env.example`.',
    '',
  ].join('\n');
}

interface WorkflowSummary {
  readonly id: string;
  readonly isSingleAgent: boolean;
}

/** Runs the first declared workflow (mirrors every other adapter's `generateMainFile`/`generateIndexFile`, which picks `[first]` from the workflow list the same way) — calling either its plain `run(task)` or `build_team()`, whichever `generate-workflow.ts` emitted for it. */
export function generateMainFile(workflows: readonly WorkflowSummary[]): string {
  const [first] = workflows;
  if (first === undefined) {
    return [
      '"""No workflows are declared in this application."""',
      '',
      'def main() -> None:',
      '    raise NotImplementedError("No workflows are declared in this application.")',
      '',
      '',
      'if __name__ == "__main__":',
      '    main()',
      '',
    ].join('\n');
  }

  const moduleName = toIdentifier(first.id);
  if (first.isSingleAgent) {
    return [
      'import asyncio',
      '',
      `from .workflows.${moduleName} import run`,
      '',
      '',
      'async def main() -> None:',
      '    result = await run(task="Hello!")',
      '    print(result)',
      '',
      '',
      'if __name__ == "__main__":',
      '    asyncio.run(main())',
      '',
    ].join('\n');
  }

  return [
    'import asyncio',
    '',
    `from .workflows.${moduleName} import build_team`,
    '',
    '',
    'async def main() -> None:',
    '    team = build_team()',
    '    result = await team.run(task="Hello!")',
    '    print(result.messages[-1].content)',
    '',
    '',
    'if __name__ == "__main__":',
    '    asyncio.run(main())',
    '',
  ].join('\n');
}
