import { isSyntacticallyValidPython } from '@agentform/compiler';
import { describe, expect, it } from 'vitest';
import { generateWorkflowFile } from './generate-workflow.js';
import { baseIR, multiAgentIR } from './test-fixtures.js';

function workflowFromFixture(ir: ReturnType<typeof baseIR>, workflowId: string) {
  const workflow = ir.workflows.get(workflowId);
  if (!workflow) {
    throw new Error(`expected fixture to declare workflow "${workflowId}"`);
  }
  return workflow;
}

describe('generateWorkflowFile', () => {
  it('includes a generated-file header naming the source resource', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(baseIR(), 'main'));
    expect(source).toContain('# Generated by Agentform.');
    expect(source).toContain('# Source: workflow.main');
  });

  describe('single-agent workflow (no team overhead)', () => {
    it('generates a plain run(task) function calling the single agent directly', () => {
      const source = generateWorkflowFile('main', workflowFromFixture(baseIR(), 'main'));
      expect(source).toContain('from ..agents.assistant import build_assistant_agent');
      expect(source).toContain('async def run(task: str) -> str:');
      expect(source).toContain('agent = build_assistant_agent()');
      expect(source).toContain('result = await agent.run(task=task)');
      expect(source).toContain('return result.messages[-1].content');
      expect(source).not.toContain('RoundRobinGroupChat');
    });

    it('produces syntactically valid Python', () => {
      const source = generateWorkflowFile('main', workflowFromFixture(baseIR(), 'main'));
      expect(isSyntacticallyValidPython(source)).toBe(true);
    });
  });

  describe('multi-participant workflow (team)', () => {
    it('builds a RoundRobinGroupChat with every agent participant', () => {
      const source = generateWorkflowFile('main', workflowFromFixture(multiAgentIR(), 'main'));
      expect(source).toContain('def build_team() -> RoundRobinGroupChat:');
      expect(source).toContain('build_intake_agent(),');
      expect(source).toContain('build_research_specialist_agent(),');
    });

    it('always includes a safety-net termination condition', () => {
      const source = generateWorkflowFile('main', workflowFromFixture(multiAgentIR(), 'main'));
      expect(source).toContain(
        'termination_condition=MaxMessageTermination(10) | TextMentionTermination("TERMINATE")',
      );
    });

    it('adds a UserProxyAgent participant for a humanApproval node, documenting its approvers', () => {
      const source = generateWorkflowFile('main', workflowFromFixture(multiAgentIR(), 'main'));
      expect(source).toContain('from autogen_agentchat.agents import UserProxyAgent');
      expect(source).toContain('UserProxyAgent(name="approve", input_func=approve_input)');
      expect(source).toContain(
        'async def approve_input(prompt: str, cancellation_token: CancellationToken | None = None) -> str:',
      );
      expect(source).toContain('Approvers: ops-team');
      expect(source).toContain('raise NotImplementedError(');
    });

    it('generates no participant for the terminate node', () => {
      const source = generateWorkflowFile('main', workflowFromFixture(multiAgentIR(), 'main'));
      expect(source).not.toContain('done');
    });

    it('imports each referenced agent once, deduplicated and sorted', () => {
      const source = generateWorkflowFile('main', workflowFromFixture(multiAgentIR(), 'main'));
      expect(source).toContain('from ..agents.intake import build_intake_agent');
      expect(source).toContain(
        'from ..agents.research_specialist import build_research_specialist_agent',
      );
      expect(source.indexOf('from ..agents.intake')).toBeLessThan(
        source.indexOf('from ..agents.research_specialist'),
      );
    });

    it('produces syntactically valid Python', () => {
      const source = generateWorkflowFile('main', workflowFromFixture(multiAgentIR(), 'main'));
      expect(isSyntacticallyValidPython(source)).toBe(true);
    });
  });
});
