import { readFileSync } from 'node:fs';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createFixtureProject, runCli, type FixtureProject } from '../test-fixture-project.js';

let fixture: FixtureProject | undefined;

afterEach(() => {
  fixture?.cleanup();
  fixture = undefined;
});

describe('agentform import', () => {
  it('exits 14 (IMPORT_FAILURE) when nothing recognizable is found', () => {
    fixture = createFixtureProject({ 'main.py': 'print("hello world")\n' });
    const result = runCli(['import'], fixture.dir);
    expect(result.exitCode).toBe(14);
    expect(result.stderr).toContain('No supported project was recognized');
  });

  it('exits 14 for a non-existent source directory', () => {
    fixture = createFixtureProject({ 'placeholder.txt': 'x' });
    const result = runCli(['import', 'does-not-exist'], fixture.dir);
    expect(result.exitCode).toBe(14);
  });

  it('recognizes a raw OpenAI Agents SDK project and writes a candidate specification', () => {
    fixture = createFixtureProject({
      'src/agent.ts': [
        "import { Agent, tool } from '@openai/agents';",
        '',
        'export const search = tool({',
        "  name: 'web_search',",
        '});',
        '',
        'export const triageAgent = new Agent({',
        "  name: 'Triage Agent',",
        "  instructions: 'Route the user to the right specialist.',",
        "  model: 'gpt-4o',",
        '});',
        '',
      ].join('\n'),
    });

    const result = runCli(['import'], fixture.dir);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('Recognized a raw OpenAI Agents SDK project');
    expect(result.stdout).toContain('Manual follow-up required');

    const written = readFileSync(path.join(fixture.dir, 'agentform.import.yaml'), 'utf-8');
    expect(written).toContain('apiVersion: agentform.dev/v1alpha1');
    expect(written).toContain('Triage_Agent');
    expect(written).toContain('gpt-4o');
  });

  it('produces a candidate specification that passes agentform validate for a simple recognized project', () => {
    fixture = createFixtureProject({
      'src/agent.ts': [
        "import { Agent } from '@openai/agents';",
        '',
        'export const assistant = new Agent({',
        "  name: 'assistant',",
        "  instructions: 'You are a helpful, concise assistant.',",
        "  model: 'gpt-5',",
        '});',
        '',
      ].join('\n'),
    });

    expect(runCli(['import'], fixture.dir).exitCode).toBe(0);

    // Promote the candidate spec to the real entry file and validate it —
    // proof the output isn't just YAML-shaped, but actually schema-valid
    // for the common case (§15.12 never *promises* this, but it should
    // work when the source is this simple).
    const candidate = readFileSync(path.join(fixture.dir, 'agentform.import.yaml'), 'utf-8');
    fixture.cleanup();
    fixture = createFixtureProject({ 'agentform.yaml': candidate });
    const validated = runCli(['validate'], fixture.dir);
    expect(validated.exitCode).toBe(0);
  });

  it('recognizes a raw LangGraph project and writes a candidate specification', () => {
    fixture = createFixtureProject({
      'src/graph.py': [
        'from langgraph.graph import StateGraph',
        '',
        'workflow = StateGraph(State)',
        'workflow.add_node("triage", triage_node)',
        'workflow.add_node("specialist", specialist_node)',
        'workflow.add_edge("triage", "specialist")',
        'workflow.set_entry_point("triage")',
        '',
      ].join('\n'),
    });

    const result = runCli(['import'], fixture.dir);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('Recognized a raw LangGraph project');

    const written = readFileSync(path.join(fixture.dir, 'agentform.import.yaml'), 'utf-8');
    expect(written).toContain('triage:');
    expect(written).toContain('specialist:');
  });

  it('recognizes a project generated by agentform compile via its manifest and header comments', () => {
    fixture = createFixtureProject({
      'manifest.json': JSON.stringify({ generatedBy: 'agentform', adapter: 'openai' }),
      'src/agents/assistant.ts': [
        '// Generated by Agentform. Do not edit by hand — re-run `agentform compile` instead.',
        '// Source: agent.assistant',
        '',
        'export const assistant = {};',
        '',
      ].join('\n'),
    });

    const result = runCli(['import'], fixture.dir);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('Recognized a generated Agentform project');
    expect(result.stdout).toContain('Confidence: 100%');
  });

  it('refuses to overwrite an existing candidate output file', () => {
    fixture = createFixtureProject({
      'agentform.import.yaml': 'placeholder: true\n',
      'src/agent.ts': "import { Agent } from '@openai/agents';\nnew Agent({ name: 'a' });",
    });

    const result = runCli(['import'], fixture.dir);
    expect(result.exitCode).toBe(14);
    expect(result.stderr).toContain('Refusing to overwrite');
  });

  it('produces parseable JSON output', () => {
    fixture = createFixtureProject({
      'src/agent.ts': "import { Agent } from '@openai/agents';\nnew Agent({ name: 'a' });",
    });

    const result = runCli(['import', '--json'], fixture.dir);
    const parsed = JSON.parse(result.stdout) as {
      success: boolean;
      recognized: string;
      candidates: unknown[];
      confidence: number;
    };
    expect(parsed.success).toBe(true);
    expect(parsed.recognized).toContain('OpenAI');
    expect(parsed.candidates.length).toBeGreaterThan(0);
    expect(parsed.confidence).toBeGreaterThan(0);
  });

  it('supports --help', () => {
    fixture = createFixtureProject({ 'placeholder.txt': 'x' });
    const result = runCli(['import', '--help'], fixture.dir);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('--out');
  });
});
