import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { inspectGeneratedAgentformProject } from './import-generated.js';

function tempProject(files: Readonly<Record<string, string>>): string {
  const dir = mkdtempSync(path.join(tmpdir(), 'agentform-import-generated-'));
  for (const [relativePath, content] of Object.entries(files)) {
    const target = path.join(dir, relativePath);
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, content, 'utf-8');
  }
  return dir;
}

let dir: string | undefined;

afterEach(() => {
  if (dir) {
    rmSync(dir, { recursive: true, force: true });
    dir = undefined;
  }
});

describe('inspectGeneratedAgentformProject', () => {
  it('does not recognize a directory with no manifest.json', () => {
    dir = tempProject({ 'src/index.ts': 'export {};' });
    const result = inspectGeneratedAgentformProject(dir);
    expect(result.recognized).toBe(false);
  });

  it('does not recognize a manifest.json not written by agentform', () => {
    dir = tempProject({ 'manifest.json': JSON.stringify({ generatedBy: 'something-else' }) });
    const result = inspectGeneratedAgentformProject(dir);
    expect(result.recognized).toBe(false);
  });

  it('does not recognize an unparseable manifest.json', () => {
    dir = tempProject({ 'manifest.json': 'not json{{' });
    const result = inspectGeneratedAgentformProject(dir);
    expect(result.recognized).toBe(false);
  });

  it('recovers resource addresses from generated-file header comments', () => {
    dir = tempProject({
      'manifest.json': JSON.stringify({ generatedBy: 'agentform', adapter: 'openai' }),
      'src/agents/assistant.ts': [
        '// Generated by Agentform. Do not edit by hand — re-run `agentform compile` instead.',
        '// Source: agent.assistant',
        '',
        'export const assistant = {};',
        '',
      ].join('\n'),
      'src/tools/search.ts': [
        '// Generated by Agentform. Do not edit by hand — re-run `agentform compile` instead.',
        '// Source: tool.search',
        '',
      ].join('\n'),
    });

    const result = inspectGeneratedAgentformProject(dir);
    expect(result.recognized).toBe(true);
    const addresses = result.candidates.map((c) => c.resourceAddress).sort();
    expect(addresses).toEqual(['agent.assistant', 'tool.search']);
    expect(result.candidates.every((c) => c.confidence === 1)).toBe(true);
  });

  it('recognizes a Python (# Source:) header comment the same way', () => {
    dir = tempProject({
      'manifest.json': JSON.stringify({ generatedBy: 'agentform', adapter: 'langgraph' }),
      'src/agents/assistant.py': [
        '# Generated by Agentform. Do not edit by hand — re-run `agentform compile` instead.',
        '# Source: agent.assistant',
        '',
      ].join('\n'),
    });

    const result = inspectGeneratedAgentformProject(dir);
    expect(result.candidates.map((c) => c.resourceAddress)).toEqual(['agent.assistant']);
  });

  it('handles a header listing multiple source addresses on one line', () => {
    dir = tempProject({
      'manifest.json': JSON.stringify({ generatedBy: 'agentform' }),
      'src/index.ts': '// Source: agent.assistant, model.primary\n',
    });

    const result = inspectGeneratedAgentformProject(dir);
    expect(result.candidates.map((c) => c.resourceAddress).sort()).toEqual([
      'agent.assistant',
      'model.primary',
    ]);
  });

  it('deduplicates the same address appearing in multiple files', () => {
    dir = tempProject({
      'manifest.json': JSON.stringify({ generatedBy: 'agentform' }),
      'a.ts': '// Source: agent.assistant\n',
      'b.ts': '// Source: agent.assistant\n',
    });

    const result = inspectGeneratedAgentformProject(dir);
    expect(result.candidates).toHaveLength(1);
  });

  it('always reports unsupported constructs and manual actions when recognized', () => {
    dir = tempProject({
      'manifest.json': JSON.stringify({ generatedBy: 'agentform', adapter: 'openai' }),
      'a.ts': '// Source: agent.assistant\n',
    });
    const result = inspectGeneratedAgentformProject(dir);
    expect(result.unsupportedConstructs.length).toBeGreaterThan(0);
    expect(result.manualActions.length).toBeGreaterThan(0);
  });
});
