import { commonFiles, readme, type ProjectTemplate, type TemplateContext } from './types.js';

export const governmentComplaintWorkflowTemplate: ProjectTemplate = {
  id: 'government-complaint',
  title: 'Government complaint workflow',
  description:
    'A municipal complaint intake assistant: location lookup, duplicate-aware submission, and a human approval gate for low-confidence classifications — the canonical regulated-government example.',
  requiredEnvVars: ['COMPLAINT_API_URL'],
  files(context: TemplateContext) {
    const agentform = [
      'apiVersion: agentform.dev/v1alpha1',
      'kind: AgenticApplication',
      '',
      'metadata:',
      `  name: ${context.name}`,
      '  version: 1.0.0',
      '  description: Processes citizen complaints',
      '  labels:',
      '    domain: government',
      '    data-classification: restricted',
      '',
      'spec:',
      '  runtime:',
      `    target: ${context.target}`,
      '    environment: development',
      '',
      '  models:',
      '    primary:',
      '      provider: openai',
      '      model: gpt-5',
      '      temperature: 0',
      '      responseFormat:',
      '        schemaRef: schemas/complaint.json',
      '',
      '  tools:',
      '    locationLookup:',
      '      type: mcp',
      '      server: municipal-services',
      '      operation: location.lookup',
      '      sideEffect: read',
      '      timeout: 10s',
      '    complaintRegistry:',
      '      type: http',
      '      baseUrl: ${env.COMPLAINT_API_URL}',
      '      operations:',
      '        create:',
      '          method: POST',
      '          path: /complaints',
      '        search:',
      '          method: GET',
      '          path: /complaints',
      '      sideEffect: write',
      '      permissions:',
      '        - complaints:write',
      '      timeout: 15s',
      '',
      '  agents:',
      '    intake:',
      '      model: primary',
      '      role: complaint-intake',
      '      instructions:',
      '        file: prompts/intake.md',
      '      tools:',
      '        - locationLookup',
      '        - complaintRegistry',
      '      limits:',
      '        maxSteps: 8',
      '        timeout: 30s',
      '        maxCostUsd: 0.15',
      '',
      '  workflows:',
      '    main:',
      '      entrypoint: intake',
      '      nodes:',
      '        intake:',
      '          type: agent',
      '          agent: intake',
      '        approval:',
      '          type: humanApproval',
      '          timeout: 24h',
      '        submit:',
      '          type: tool',
      '          tool: complaintRegistry.create',
      '      edges:',
      '        - from: intake',
      '          to: approval',
      '          when: output.confidence < 0.85',
      '        - from: intake',
      '          to: submit',
      '          when: output.confidence >= 0.85',
      '        - from: approval',
      '          to: submit',
      '          when: approval.status == "approved"',
      '',
      '  policies:',
      '    - require-human-approval-for-write',
      '    - restrict-data-residency',
      '',
      '  evaluations:',
      '    datasets:',
      '      - tests/complaints.jsonl',
      '    thresholds:',
      '      taskSuccess: 0.92',
      '      policyViolations: 0',
      '      maximumAverageCostUsd: 0.10',
      '',
      '  observability:',
      '    tracing:',
      '      provider: opentelemetry',
      '    recordPrompts: false',
      '    recordToolCalls: true',
      '',
    ].join('\n');

    const intakePrompt = [
      '# Complaint intake agent',
      '',
      'You are a municipal complaint intake assistant. For every citizen complaint:',
      '',
      '1. Look up the reported location with the `locationLookup` tool.',
      '2. Search existing complaints for duplicates before creating a new one.',
      '3. Classify the complaint and report a confidence score between 0 and 1.',
      '4. Only call `complaintRegistry.create` when you are not creating a duplicate.',
      '',
      'Respond in the structured format described by `schemas/complaint.json`.',
      '',
    ].join('\n');

    const complaintSchema = `${JSON.stringify(
      {
        $schema: 'http://json-schema.org/draft-07/schema#',
        type: 'object',
        required: ['category', 'confidence', 'locationId'],
        properties: {
          category: { type: 'string' },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
          locationId: { type: 'string' },
          description: { type: 'string' },
        },
      },
      null,
      2,
    )}\n`;

    return {
      ...commonFiles(governmentComplaintWorkflowTemplate),
      'agentform.yaml': agentform,
      'prompts/intake.md': intakePrompt,
      'schemas/complaint.json': complaintSchema,
      'README.md': readme(context, governmentComplaintWorkflowTemplate),
    };
  },
};
