import { commonFiles, readme, type ProjectTemplate, type TemplateContext } from './types.js';

export const humanApprovalWorkflowTemplate: ProjectTemplate = {
  id: 'human-approval',
  title: 'Human approval workflow',
  description:
    'An agent whose low-confidence outputs are routed to a human approval gate before a write tool runs.',
  requiredEnvVars: ['REGISTRY_API_URL'],
  files(context: TemplateContext) {
    const agentform = [
      'apiVersion: agentform.dev/v1alpha1',
      'kind: AgenticApplication',
      '',
      'metadata:',
      `  name: ${context.name}`,
      '  version: 1.0.0',
      '  description: Drafts an action and requires human approval before anything is written.',
      '',
      'spec:',
      '  runtime:',
      `    target: ${context.target}`,
      '    environment: development',
      '',
      '  models:',
      '    primary:',
      '      provider: openai',
      '      model: gpt-5',
      '      temperature: 0',
      '',
      '  tools:',
      '    registry:',
      '      type: http',
      '      baseUrl: ${env.REGISTRY_API_URL}',
      '      operations:',
      '        create:',
      '          method: POST',
      '          path: /records',
      '      sideEffect: write',
      '      permissions:',
      '        - records:write',
      '      timeout: 15s',
      '',
      '  agents:',
      '    drafter:',
      '      model: primary',
      '      role: drafter',
      '      instructions:',
      "        text: You draft a record from the user's request and report a confidence score.",
      '      limits:',
      '        maxSteps: 6',
      '        timeout: 30s',
      '        maxCostUsd: 0.10',
      '',
      '  workflows:',
      '    main:',
      '      entrypoint: draft',
      '      nodes:',
      '        draft:',
      '          type: agent',
      '          agent: drafter',
      '        approve:',
      '          type: humanApproval',
      '          timeout: 24h',
      '        submit:',
      '          type: tool',
      '          tool: registry.create',
      '        rejected:',
      '          type: terminate',
      '          reason: rejected by approver',
      '      edges:',
      '        - from: draft',
      '          to: approve',
      '          when: output.confidence < 0.85',
      '        - from: draft',
      '          to: submit',
      '          when: output.confidence >= 0.85',
      '        - from: approve',
      '          to: submit',
      '          when: approval.status == "approved"',
      '        - from: approve',
      '          to: rejected',
      '          when: approval.status == "rejected"',
      '',
      '  policies:',
      '    - require-human-approval-for-write',
      '',
    ].join('\n');

    return {
      ...commonFiles(humanApprovalWorkflowTemplate),
      'agentform.yaml': agentform,
      'README.md': readme(context, humanApprovalWorkflowTemplate),
    };
  },
};
