import { commonFiles, readme, type ProjectTemplate, type TemplateContext } from './types.js';

export const multiAgentWorkflowTemplate: ProjectTemplate = {
  id: 'multi-agent',
  title: 'Multi-agent research workflow',
  description:
    'A researcher and a writer agent, with a bounded review loop between drafting and finishing.',
  files(context: TemplateContext) {
    const agentform = [
      'apiVersion: agentform.dev/v1alpha1',
      'kind: AgenticApplication',
      '',
      'metadata:',
      `  name: ${context.name}`,
      '  version: 1.0.0',
      '  description: Researches a topic, drafts a summary, and revises it up to a fixed number of times.',
      '',
      'spec:',
      '  runtime:',
      `    target: ${context.target}`,
      '    environment: development',
      '',
      '  models:',
      '    primary:',
      '      provider: openai',
      '      model: gpt-5',
      '      temperature: 0.2',
      '',
      '  tools:',
      '    search:',
      '      type: mcp',
      '      server: search-service',
      '      operation: search.query',
      '      sideEffect: read',
      '      timeout: 10s',
      '',
      '  agents:',
      '    researcher:',
      '      model: primary',
      '      role: researcher',
      '      instructions:',
      '        text: You research the given topic using the search tool and produce source notes.',
      '      tools:',
      '        - search',
      '      limits:',
      '        maxSteps: 8',
      '        timeout: 45s',
      '        maxCostUsd: 0.20',
      '    writer:',
      '      model: primary',
      '      role: writer',
      '      instructions:',
      '        text: You turn research notes into a clear summary, revising when asked.',
      '      limits:',
      '        maxSteps: 4',
      '        timeout: 30s',
      '        maxCostUsd: 0.10',
      '',
      '  workflows:',
      '    main:',
      '      entrypoint: research',
      '      nodes:',
      '        research:',
      '          type: agent',
      '          agent: researcher',
      '        draft:',
      '          type: agent',
      '          agent: writer',
      '        reviewLoop:',
      '          type: loop',
      '          maxIterations: 3',
      '        done:',
      '          type: terminate',
      '      edges:',
      '        - from: research',
      '          to: draft',
      '        - from: draft',
      '          to: reviewLoop',
      '        - from: reviewLoop',
      '          to: draft',
      '          when: needsRevision',
      '        - from: reviewLoop',
      '          to: done',
      '          when: "!needsRevision"',
      '',
    ].join('\n');

    return {
      ...commonFiles(multiAgentWorkflowTemplate),
      'agentform.yaml': agentform,
      'README.md': readme(context, multiAgentWorkflowTemplate),
    };
  },
};
