import { commonFiles, readme, type ProjectTemplate, type TemplateContext } from './types.js';

export const toolUsingAgentTemplate: ProjectTemplate = {
  id: 'tool-agent',
  title: 'Tool-using agent',
  description: 'A single agent with one MCP tool it is explicitly granted permission to call.',
  files(context: TemplateContext) {
    const agentform = [
      'apiVersion: agentform.dev/v1alpha1',
      'kind: AgenticApplication',
      '',
      'metadata:',
      `  name: ${context.name}`,
      '  version: 1.0.0',
      '  description: A single agent that looks things up with a search tool before answering.',
      '',
      'spec:',
      '  runtime:',
      `    target: ${context.target}`,
      '    environment: development',
      '',
      '  models:',
      '    primary:',
      '      provider: openai',
      '      model: gpt-5',
      '      temperature: 0',
      '',
      '  tools:',
      '    search:',
      '      type: mcp',
      '      server: search-service',
      '      operation: search.query',
      '      sideEffect: read',
      '      timeout: 10s',
      '',
      '  agents:',
      '    researcher:',
      '      model: primary',
      '      role: researcher',
      '      instructions:',
      '        text: You answer questions by searching first, then citing what you found.',
      '      tools:',
      '        - search',
      '      limits:',
      '        maxSteps: 6',
      '        timeout: 30s',
      '        maxCostUsd: 0.10',
      '',
      '  workflows:',
      '    main:',
      '      entrypoint: researcher',
      '      nodes:',
      '        researcher:',
      '          type: agent',
      '          agent: researcher',
      '',
    ].join('\n');

    return {
      ...commonFiles(toolUsingAgentTemplate),
      'agentform.yaml': agentform,
      'README.md': readme(context, toolUsingAgentTemplate),
    };
  },
};
