export interface TemplateContext {
  readonly name: string;
  readonly target: string;
}

export interface ProjectTemplate {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  /** Names of `${env.*}` variables this template's `agentform.yaml` references, if any — documented in the generated `.env.example`/README rather than left for the user to discover via a validation failure. */
  readonly requiredEnvVars?: readonly string[];
  /** Relative path → file content. A template with no `requiredEnvVars` must pass `agentform validate` immediately after `agentform init`; one that does will only pass once those variables are set, exactly like `terraform apply` needing variables configured first — that's the honest behavior for a project that genuinely points at an external API. */
  files(context: TemplateContext): Record<string, string>;
}

export function commonFiles(template: ProjectTemplate): Record<string, string> {
  const envVars = template.requiredEnvVars ?? [];
  const envExample =
    envVars.length > 0
      ? `${envVars.map((name) => `${name}=`).join('\n')}\n`
      : '# This template references no ${env.*} variables.\n';

  return {
    '.gitignore': ['.agentform/', '*.afplan', '.env', '.env.*', '!.env.example', '*.log', ''].join(
      '\n',
    ),
    '.env.example': envExample,
  };
}

export function readme(context: TemplateContext, template: ProjectTemplate): string {
  const envVars = template.requiredEnvVars ?? [];
  const setupSection =
    envVars.length > 0
      ? [
          '## Setup',
          '',
          `This project references ${envVars.length === 1 ? 'an environment variable' : 'environment variables'} that must be set before \`agentform validate\` will succeed — copy \`.env.example\` to \`.env\` and fill in:`,
          '',
          ...envVars.map((name) => `- \`${name}\``),
          '',
        ]
      : [];

  return [
    `# ${context.name}`,
    '',
    template.description,
    '',
    ...setupSection,
    '## Getting started',
    '',
    '```bash',
    'agentform validate',
    'agentform graph',
    '```',
    '',
    `Generated by \`agentform init --template ${template.id}\`.`,
    '',
  ].join('\n');
}
