import { describe, expect, it } from 'vitest';
import { generateWorkflowFile } from './generate-workflow.js';
import { baseIR, graphWorkflowIR } from './test-fixtures.js';
import { isSyntacticallyValidPython } from '@agentform/compiler';

function workflowFromFixture(ir: ReturnType<typeof graphWorkflowIR>, workflowId: string) {
  const workflow = ir.workflows.get(workflowId);
  if (!workflow) {
    throw new Error(`expected fixture to declare workflow "${workflowId}"`);
  }
  return workflow;
}

describe('generateWorkflowFile', () => {
  it('includes a generated-file header naming the source resource', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(baseIR(), 'main'));
    expect(source).toContain('# Generated by Agentform.');
    expect(source).toContain('# Source: workflow.main');
  });

  it('wires the entrypoint from START', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(graphWorkflowIR(), 'main'));
    expect(source).toContain('builder.add_edge(START, "triage")');
  });

  it('registers every node with add_node', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(graphWorkflowIR(), 'main'));
    expect(source).toContain('builder.add_node("triage", triage_node)');
    expect(source).toContain('builder.add_node("use-search", ToolNode([search_registry]))');
    expect(source).toContain('builder.add_node("route", route_node)');
    expect(source).toContain('builder.add_node("research", researcher_node)');
    expect(source).toContain('builder.add_node("retry", retry_node)');
    expect(source).toContain('builder.add_node("approve", approve_node)');
    expect(source).toContain('builder.add_node("done", done_node)');
  });

  it('imports each referenced agent and tool function, deduplicated and sorted', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(graphWorkflowIR(), 'main'));
    expect(source).toContain('from ..agents.researcher import researcher_node');
    expect(source).toContain('from ..agents.triage import triage_node');
    expect(source).toContain('from ..tools.search_registry import search_registry');
    expect(source).toContain('from langgraph.prebuilt import ToolNode');
  });

  it('wires a single unconditional edge with plain add_edge', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(graphWorkflowIR(), 'main'));
    expect(source).toContain('builder.add_edge("triage", "use-search")');
    expect(source).toContain('builder.add_edge("use-search", "route")');
    expect(source).toContain('builder.add_edge("research", "retry")');
    expect(source).toContain('builder.add_edge("approve", "done")');
  });

  it('wires a sink node (no outgoing edges) to END', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(graphWorkflowIR(), 'main'));
    expect(source).toContain('builder.add_edge("done", END)');
  });

  it('wires a router node with add_conditional_edges and a stub path function', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(graphWorkflowIR(), 'main'));
    expect(source).toContain('def route_path(state: State) -> str:');
    expect(source).toContain('state.needsResearch == true');
    expect(source).toContain('state.needsResearch == false');
    expect(source).toContain(
      'builder.add_conditional_edges(\n        "route",\n        route_path,',
    );
    expect(source).toContain('            "research": "research"');
    expect(source).toContain('            "approve": "approve"');
  });

  it('generates a real (non-stub) pass-through body for the router node itself', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(graphWorkflowIR(), 'main'));
    expect(source).toContain('def route_node(state: State) -> dict:');
    expect(source).toMatch(
      /def route_node\(state: State\) -> dict:\n {4}""".*?""".*?\n {4}return \{\}/s,
    );
  });

  it('generates a real (mechanical) iteration-counter increment for the loop node', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(graphWorkflowIR(), 'main'));
    expect(source).toContain('def retry_node(state: State) -> dict:');
    expect(source).toContain(
      'return {"main_retry_iterations": state.get("main_retry_iterations", 0) + 1}',
    );
  });

  it('wires the loop node with add_conditional_edges back to the router and forward to approval', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(graphWorkflowIR(), 'main'));
    expect(source).toContain('def retry_path(state: State) -> str:');
    expect(source).toContain(
      'builder.add_conditional_edges(\n        "retry",\n        retry_path,',
    );
    expect(source).toContain('            "route": "route"');
  });

  it('calls interrupt() for the human approval node and documents its approvers', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(graphWorkflowIR(), 'main'));
    expect(source).toContain('from langgraph.types import interrupt');
    expect(source).toContain('def approve_node(state: State) -> dict:');
    expect(source).toContain('decision = interrupt(');
    expect(source).toContain('Approvers: ops-team');
    expect(source).toContain('raise NotImplementedError(');
  });

  it('generates a real (non-stub) pass-through body for the terminate node', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(graphWorkflowIR(), 'main'));
    expect(source).toMatch(
      /def done_node\(state: State\) -> dict:\n {4}""".*?""".*?\n {4}return \{\}/s,
    );
  });

  it('never imports ToolNode or interrupt when the workflow has no tool or humanApproval nodes', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(baseIR(), 'main'));
    expect(source).not.toContain('ToolNode');
    expect(source).not.toContain('interrupt');
  });

  it('defines build_graph() returning the assembled StateGraph', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(baseIR(), 'main'));
    expect(source).toContain('def build_graph() -> StateGraph:');
    expect(source).toContain('builder = StateGraph(State)');
    expect(source).toContain('return builder');
  });

  it('produces syntactically valid Python for the full graph fixture (every node type)', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(graphWorkflowIR(), 'main'));
    expect(isSyntacticallyValidPython(source)).toBe(true);
  });
});
