import { describe, expect, it } from 'vitest';
import { generateToolFile } from './generate-tool.js';
import { graphWorkflowIR } from './test-fixtures.js';
import { isSyntacticallyValidPython } from './test-syntax-check.js';

function toolFromFixture(toolId: string) {
  const ir = graphWorkflowIR();
  const tool = ir.tools.get(toolId);
  if (!tool) {
    throw new Error(`expected fixture to declare tool "${toolId}"`);
  }
  return tool;
}

describe('generateToolFile', () => {
  it('produces a @tool-decorated function named after the tool id', () => {
    const source = generateToolFile('search-registry', toolFromFixture('search-registry'));
    expect(source).toContain('@tool');
    expect(source).toContain('def search_registry(query: str) -> Any:');
  });

  it('includes a generated-file header naming the source resource', () => {
    const source = generateToolFile('search-registry', toolFromFixture('search-registry'));
    expect(source).toContain('# Generated by Agentform.');
    expect(source).toContain('# Source: tool.search-registry');
  });

  it('never fabricates real tool logic — always a NotImplementedError stub', () => {
    const source = generateToolFile('search-registry', toolFromFixture('search-registry'));
    expect(source).toContain('raise NotImplementedError(');
    expect(source).toContain('TODO: implement "search-registry"');
  });

  it('falls back to **kwargs: Any when the tool has no inputSchema', () => {
    const source = generateToolFile('no-schema-tool', {
      type: 'function',
      handler: 'noop.ts#run',
    } as never);
    expect(source).toContain('def no_schema_tool(**kwargs: Any) -> Any:');
  });

  it('only imports the typing names it actually uses', () => {
    const source = generateToolFile('no-schema-tool', {
      type: 'function',
      handler: 'noop.ts#run',
    } as never);
    expect(source).toContain('from typing import Any\n');
    expect(source).not.toContain('Optional');
    expect(source).not.toContain('Literal');
  });

  it('produces syntactically valid Python', () => {
    const source = generateToolFile('search-registry', toolFromFixture('search-registry'));
    expect(isSyntacticallyValidPython(source)).toBe(true);
  });
});
