import { describe, expect, it } from 'vitest';
import { collectLoopCounterFields, generateStateFile } from './generate-state.js';
import { baseIR, graphWorkflowIR } from './test-fixtures.js';
import { isSyntacticallyValidPython } from '@agentform/compiler';

describe('collectLoopCounterFields', () => {
  it('returns no fields when there are no loop nodes', () => {
    expect(collectLoopCounterFields(baseIR())).toEqual([]);
  });

  it('collects one field per loop node, prefixed by workflow id', () => {
    const fields = collectLoopCounterFields(graphWorkflowIR());
    expect(fields).toEqual([
      { fieldName: 'main_retry_iterations', workflowId: 'main', nodeId: 'retry', maxIterations: 3 },
    ]);
  });
});

describe('generateStateFile', () => {
  it('always declares the messages field using add_messages', () => {
    const source = generateStateFile(baseIR());
    expect(source).toContain('class State(TypedDict):');
    expect(source).toContain('messages: Annotated[list, add_messages]');
    expect(source).toContain('from langgraph.graph.message import add_messages');
  });

  it('adds an int counter field per loop node', () => {
    const source = generateStateFile(graphWorkflowIR());
    expect(source).toContain('main_retry_iterations: int');
  });

  it('omits counter fields entirely when there are no loop nodes', () => {
    const source = generateStateFile(baseIR());
    expect(source).not.toContain('_iterations');
  });

  it('includes a generated-file header', () => {
    const source = generateStateFile(baseIR());
    expect(source).toContain('# Generated by Agentform.');
  });

  it('produces syntactically valid Python', () => {
    expect(isSyntacticallyValidPython(generateStateFile(graphWorkflowIR()))).toBe(true);
  });
});
