import { describe, expect, it } from 'vitest';
import { generateAgentFile } from './generate-agent.js';
import { graphWorkflowIR } from './test-fixtures.js';
import { isSyntacticallyValidPython } from '@agentform/compiler';

function agentFromFixture(agentId: string) {
  const ir = graphWorkflowIR();
  const agent = ir.agents.get(agentId);
  if (!agent) {
    throw new Error(`expected fixture to declare agent "${agentId}"`);
  }
  return agent;
}

describe('generateAgentFile', () => {
  it('produces a node function named after the agent id', () => {
    const source = generateAgentFile('triage', agentFromFixture('triage'));
    expect(source).toContain('def triage_node(state: State) -> dict[str, Any]:');
  });

  it('documents role, model, tools, and instructions in the docstring', () => {
    const source = generateAgentFile('triage', agentFromFixture('triage'));
    expect(source).toContain('Role: triage');
    expect(source).toContain('Model: primary');
    expect(source).toContain('Tools: search-registry');
    expect(source).toContain('Instructions: Triage the incoming request.');
  });

  it('imports State from the sibling state module', () => {
    const source = generateAgentFile('triage', agentFromFixture('triage'));
    expect(source).toContain('from ..state import State');
  });

  it('never fabricates real model-calling logic — always a NotImplementedError stub', () => {
    const source = generateAgentFile('triage', agentFromFixture('triage'));
    expect(source).toContain('raise NotImplementedError(');
    expect(source).toContain('\'Agent "triage" is not yet implemented.\'');
  });

  it('omits the Tools line for an agent with no declared tools', () => {
    const source = generateAgentFile('researcher', agentFromFixture('researcher'));
    expect(source).not.toContain('Tools:');
  });

  it('includes a generated-file header naming the source resource', () => {
    const source = generateAgentFile('triage', agentFromFixture('triage'));
    expect(source).toContain('# Generated by Agentform.');
    expect(source).toContain('# Source: agent.triage');
  });

  it('produces syntactically valid Python', () => {
    const source = generateAgentFile('triage', agentFromFixture('triage'));
    expect(isSyntacticallyValidPython(source)).toBe(true);
  });
});
