import { toIdentifier } from '@agentform/compiler';
import type { AgentformIR } from '@agentform/ir';
import { LANGGRAPH_VERSION, PYTHON_VERSION_REQUIREMENT } from './versions.js';

/**
 * A real, verified-installable `pyproject.toml`: `hatchling` +
 * `packages = ["src"]` is what makes `pip install .` work when the actual
 * package directory is named `src` (rather than the project's own name) —
 * confirmed with a real `pip install .` against the generated layout,
 * installing into `site-packages/src/` and importing cleanly from outside
 * the project directory. Running via `python -m src.main` from the project
 * root (this project's documented, primary workflow — see `README.md`)
 * doesn't actually need this install step; it's here so `pip install .`
 * also works for anyone who prefers that.
 */
export function generatePyprojectToml(ir: AgentformIR): string {
  return [
    '[project]',
    `name = ${JSON.stringify(ir.application.name)}`,
    `version = ${JSON.stringify(ir.application.version)}`,
    `requires-python = ${JSON.stringify(PYTHON_VERSION_REQUIREMENT)}`,
    'dependencies = [',
    `    ${JSON.stringify(`langgraph==${LANGGRAPH_VERSION}`)},`,
    ']',
    '',
    '[build-system]',
    'requires = ["hatchling"]',
    'build-backend = "hatchling.build"',
    '',
    '[tool.hatch.build.targets.wheel]',
    'packages = ["src"]',
    '',
  ].join('\n');
}

/**
 * Unlike the OpenAI adapter's `.env.example` (which can name a single,
 * fixed `OPENAI_API_KEY` — the SDK's own default), Agentform's
 * `model.provider` is a free-form string (`@agentform/schema`), so there is
 * no single credential env var to name here without guessing. This
 * documents the declared models instead, as a real starting point.
 */
export function generateEnvExample(ir: AgentformIR): string {
  const lines = [
    '# Agent nodes are generated as stubs (see src/agents/) — wire up your',
    "model provider(s) of choice and set their credentials here. Nothing in",
    'generated code reads these automatically; this file is a starting point.',
  ].map((line) => `# ${line}`);
  const modelLines = [...ir.models.entries()].map(
    ([id, model]) => `# ${id}: provider=${model.provider} model=${model.model}`,
  );
  return [...lines, '#', ...modelLines, ''].join('\n');
}

export function generateReadme(ir: AgentformIR): string {
  return [
    `# ${ir.application.name} (LangGraph)`,
    '',
    'Generated by [Agentform](https://github.com/YASSERRMD/AgentForm) — do not edit the files under `src/` by hand; re-run `agentform compile --target langgraph` instead.',
    '',
    '## Setup',
    '',
    '```bash',
    `python3 -m venv .venv && source .venv/bin/activate  # requires Python ${PYTHON_VERSION_REQUIREMENT}`,
    `pip install langgraph==${LANGGRAPH_VERSION}`,
    'cp .env.example .env   # then fill in your model provider credentials',
    '```',
    '',
    '## Run',
    '',
    '```bash',
    'python -m src.main',
    '```',
    '',
    '`pip install .` also works (see `pyproject.toml`) if you prefer an installed package over running from the project root.',
    '',
    '## Human approval',
    '',
    'Nodes generated from `humanApproval` workflow nodes call `interrupt()` to',
    'pause the graph. Resume a paused run with `graph.invoke(Command(resume=...), config)`',
    '— see the [LangGraph human-in-the-loop guide](https://langchain-ai.github.io/langgraph/).',
    'Pausing/resuming only works with a persistent checkpointer in place of the',
    'generated `MemorySaver` (which does not survive process restarts).',
    '',
    '## Test',
    '',
    'This project has no generated tests — add your own and wire up a test runner of your choice (e.g. `pytest`).',
    '',
    '## Security',
    '',
    '- Agent and tool node bodies are generated as `NotImplementedError` stubs; nothing runs until you implement them.',
    '- Routing functions for conditional edges (routers and loops) are also stubs — Agentform has no expression evaluator for `when` conditions.',
    '- No credentials are embedded in generated code — see `.env.example`.',
    '',
  ].join('\n');
}

/** Runs the first declared workflow (mirrors `@agentform/adapter-openai`'s `generateIndexFile`, which picks `[first]` from the workflow list the same way). */
export function generateMainFile(workflowIds: readonly string[]): string {
  const [first] = workflowIds;
  if (first === undefined) {
    return [
      '"""No workflows are declared in this application."""',
      '',
      'def main() -> None:',
      '    raise NotImplementedError("No workflows are declared in this application.")',
      '',
      '',
      'if __name__ == "__main__":',
      '    main()',
      '',
    ].join('\n');
  }
  return [
    'import uuid',
    '',
    'from langgraph.checkpoint.memory import MemorySaver',
    '',
    `from .workflows.${toIdentifier(first)} import build_graph`,
    '',
    '',
    'def main() -> None:',
    '    graph = build_graph().compile(checkpointer=MemorySaver())',
    '    # A checkpointer requires a thread_id to know which conversation to',
    '    # save/resume — a fresh one each run starts a new conversation; reuse',
    '    # the same thread_id to resume one (e.g. after a human-approval pause).',
    '    config = {"configurable": {"thread_id": str(uuid.uuid4())}}',
    '    result = graph.invoke({"messages": []}, config)',
    '    print(result)',
    '',
    '',
    'if __name__ == "__main__":',
    '    main()',
    '',
  ].join('\n');
}
