import { toPascalCase } from '@agentform/compiler';
import type { AgentformIR } from '@agentform/ir';
import {
  DOTNET_TARGET_FRAMEWORK,
  MICROSOFT_AGENTS_AI_OPENAI_VERSION,
  MICROSOFT_AGENTS_AI_VERSION,
  MICROSOFT_AGENTS_AI_WORKFLOWS_VERSION,
  OPENAI_DOTNET_VERSION,
} from './versions.js';

/** A real, buildable `.csproj` — verified end-to-end via a real `dotnet build` against these exact package versions on the installed net10.0 SDK. Includes `Microsoft.Agents.AI.OpenAI`/`OpenAI` proactively (mirroring `@agentform/adapter-autogen`'s `autogen-ext[openai]` inclusion) so the model-client stub's TODO comment can point at an already-referenced package. */
export function generateCsproj(ir: AgentformIR): string {
  return [
    '<Project Sdk="Microsoft.NET.Sdk">',
    '',
    '  <PropertyGroup>',
    `    <AssemblyName>${toPascalCase(ir.application.name)}</AssemblyName>`,
    '    <OutputType>Exe</OutputType>',
    `    <TargetFramework>${DOTNET_TARGET_FRAMEWORK}</TargetFramework>`,
    '    <ImplicitUsings>enable</ImplicitUsings>',
    '    <Nullable>enable</Nullable>',
    '  </PropertyGroup>',
    '',
    '  <ItemGroup>',
    `    <PackageReference Include="Microsoft.Agents.AI" Version="${MICROSOFT_AGENTS_AI_VERSION}" />`,
    `    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="${MICROSOFT_AGENTS_AI_OPENAI_VERSION}" />`,
    `    <PackageReference Include="Microsoft.Agents.AI.Workflows" Version="${MICROSOFT_AGENTS_AI_WORKFLOWS_VERSION}" />`,
    `    <PackageReference Include="OpenAI" Version="${OPENAI_DOTNET_VERSION}" />`,
    '  </ItemGroup>',
    '',
    '</Project>',
    '',
  ].join('\n');
}

/** Same reasoning as every other adapter: `model.provider` is free-form, so there's no single fixed credential env var to name without guessing — documents the declared models as a starting point, plus the one credential the model-client stub's own TODO comment can name with confidence (`OPENAI_API_KEY`, matching its suggested `OpenAIClient` snippet). */
export function generateEnvExample(ir: AgentformIR): string {
  const lines = [
    '# The model-client stub in Models/ suggests OPENAI_API_KEY as a starting',
    'point (Microsoft.Agents.AI.OpenAI is already referenced in the .csproj)',
    '— set whichever credential env var your chosen provider actually needs.',
  ];
  const modelLines = [...ir.models.entries()].map(
    ([id, model]) => `# ${id}: provider=${model.provider} model=${model.model}`,
  );
  return [
    ...lines.map((line) => `# ${line}`),
    '#',
    'OPENAI_API_KEY=',
    '#',
    '# Declared models in this application:',
    ...modelLines,
    '',
  ].join('\n');
}

export function generateReadme(ir: AgentformIR): string {
  return [
    `# ${ir.application.name} (Microsoft Agent Framework)`,
    '',
    'Generated by [Agentform](https://github.com/YASSERRMD/AgentForm) — do not edit the files under `Agents/`, `Tools/`, `Models/`, or `Workflows/` by hand; re-run `agentform compile --target microsoft` instead.',
    '',
    '## Setup',
    '',
    '```bash',
    `dotnet restore   # requires the .NET SDK for ${DOTNET_TARGET_FRAMEWORK}`,
    'cp .env.example .env   # then fill in your model provider credentials',
    '```',
    '',
    '## Run',
    '',
    '```bash',
    'dotnet run',
    '```',
    '',
    '## Delegation',
    '',
    'Agents declared with `delegation.allowedAgents` become real',
    '`HandoffWorkflowBuilder.WithHandoffs(...)` edges — unlike the other three',
    'Phase 9 targets, this precisely represents a per-agent allowlist with no',
    'sharing or crew-wide-scoping caveat. One real constraint applies: every',
    "handoff source must be reachable from the workflow's entrypoint through",
    'some chain of handoff edges (`HandoffWorkflowBuilder.Build()` throws a real',
    '`InvalidOperationException` otherwise) — `agentform compile` reports an',
    'unreachable source as a blocking diagnostic before generating code that',
    'would fail at that point.',
    '',
    '## Human approval',
    '',
    'Not generated by this adapter. Microsoft Agent Framework has two real',
    'human-in-the-loop mechanisms — tool-level `ApprovalRequiredAIFunction` /',
    '`ToolApprovalRequestContent`, and the lower-level `RequestPort<TRequest,TResponse>`',
    'for pausing a raw executor graph — but neither is a node this adapter,',
    "which targets `AgentWorkflowBuilder`'s agent-level convenience builders,",
    'can faithfully bind to a workflow graph node. Wrap the specific tool call',
    'that needs approval with `ApprovalRequiredAIFunction` by hand in the',
    "generated tool file if you need this — see the framework's",
    'human-in-the-loop docs.',
    '',
    '## Test',
    '',
    'This project has no generated tests — add your own and wire up a test project of your choice (e.g. xUnit).',
    '',
    '## Security',
    '',
    '- Model chat clients and tool bodies are generated as `NotImplementedException` stubs; nothing runs until you implement them.',
    '- No credentials are embedded in generated code — see `.env.example`.',
    '',
  ].join('\n');
}

interface WorkflowSummary {
  readonly id: string;
  readonly isSingleAgent: boolean;
}

/** Runs the first declared workflow — a plain `agent.RunAsync(...)` for a single-participant workflow, or the verified real `InProcessExecution.RunAsync(workflow, input)` + `WorkflowEvent`/`ExecutorCompletedEvent` streaming pattern otherwise. Top-level-statements style, matching the framework's own sample `Program.cs` shape. */
export function generateProgramFile(workflows: readonly WorkflowSummary[]): string {
  const [first] = workflows;
  if (first === undefined) {
    return [
      'throw new NotImplementedException("No workflows are declared in this application.");',
      '',
    ].join('\n');
  }

  const className = `${toPascalCase(first.id)}Workflow`;
  if (first.isSingleAgent) {
    return [
      'using GeneratedApp.Workflows;',
      'using Microsoft.Agents.AI;',
      '',
      `AIAgent agent = ${className}.Build();`,
      'Console.WriteLine(await agent.RunAsync("Hello!"));',
      '',
    ].join('\n');
  }

  return [
    'using GeneratedApp.Workflows;',
    'using Microsoft.Agents.AI.Workflows;',
    '',
    `Workflow workflow = ${className}.Build();`,
    'await using Run run = await InProcessExecution.RunAsync(workflow, "Hello!");',
    'foreach (WorkflowEvent evt in run.NewEvents)',
    '{',
    '    if (evt is ExecutorCompletedEvent completed)',
    '    {',
    '        Console.WriteLine($"{completed.ExecutorId}: {completed.Data}");',
    '    }',
    '}',
    '',
  ].join('\n');
}
