import { describe, expect, it } from 'vitest';
import { generateWorkflowFile, isSingleAgentWorkflow } from './generate-workflow.js';
import { baseIR, multiAgentIR, sequentialMultiAgentIR } from './test-fixtures.js';

function workflowFromFixture(ir: ReturnType<typeof baseIR>, workflowId: string) {
  const workflow = ir.workflows.get(workflowId);
  if (!workflow) {
    throw new Error(`expected fixture to declare workflow "${workflowId}"`);
  }
  return workflow;
}

describe('generateWorkflowFile', () => {
  it('includes a generated-file header naming the source resource', () => {
    const ir = baseIR();
    const source = generateWorkflowFile('main', workflowFromFixture(ir, 'main'), ir);
    expect(source).toContain('// Generated by Agentform.');
    expect(source).toContain('// Source: workflow.main');
  });

  it('single-agent workflows return a bare AIAgent, no Workflow wrapper', () => {
    const ir = baseIR();
    expect(isSingleAgentWorkflow(workflowFromFixture(ir, 'main'))).toBe(true);
    const source = generateWorkflowFile('main', workflowFromFixture(ir, 'main'), ir);
    expect(source).toContain(
      'public static AIAgent Build() => GeneratedApp.Agents.AssistantAgent.Build();',
    );
    expect(source).not.toContain('Microsoft.Agents.AI.Workflows');
    expect(source).not.toContain('public static Workflow Build()');
  });

  it('reachable delegation produces a real HandoffWorkflowBuilder wiring', () => {
    const ir = multiAgentIR();
    expect(isSingleAgentWorkflow(workflowFromFixture(ir, 'main'))).toBe(false);
    const source = generateWorkflowFile('main', workflowFromFixture(ir, 'main'), ir);
    expect(source).toContain(
      'HandoffWorkflowBuilder builder = AgentWorkflowBuilder.CreateHandoffBuilderWith(intake);',
    );
    expect(source).toContain('builder.WithHandoffs([intake], researchSpecialist);');
    expect(source).toContain('builder.EnableReturnToPrevious();');
    expect(source).toContain('return builder.Build();');
  });

  it('no declared delegation among participants falls back to BuildSequential', () => {
    const ir = sequentialMultiAgentIR();
    const source = generateWorkflowFile('main', workflowFromFixture(ir, 'main'), ir);
    expect(source).toContain('return AgentWorkflowBuilder.BuildSequential([drafter, editor]);');
    expect(source).not.toContain('HandoffWorkflowBuilder');
  });

  it('constructs each participating agent exactly once', () => {
    const ir = multiAgentIR();
    const source = generateWorkflowFile('main', workflowFromFixture(ir, 'main'), ir);
    expect(source.match(/GeneratedApp\.Agents\.IntakeAgent\.Build\(\)/g)).toHaveLength(1);
    expect(source.match(/GeneratedApp\.Agents\.ResearchSpecialistAgent\.Build\(\)/g)).toHaveLength(
      1,
    );
  });
});
