import { isSyntacticallyValidPython } from '@agentform/compiler';
import { describe, expect, it } from 'vitest';
import { generateWorkflowFile } from './generate-workflow.js';
import { baseIR, multiAgentIR } from './test-fixtures.js';

function workflowFromFixture(ir: ReturnType<typeof baseIR>, workflowId: string) {
  const workflow = ir.workflows.get(workflowId);
  if (!workflow) {
    throw new Error(`expected fixture to declare workflow "${workflowId}"`);
  }
  return workflow;
}

describe('generateWorkflowFile', () => {
  it('includes a generated-file header naming the source resource', () => {
    const ir = baseIR();
    const source = generateWorkflowFile('main', workflowFromFixture(ir, 'main'), ir);
    expect(source).toContain('# Generated by Agentform.');
    expect(source).toContain('# Source: workflow.main');
  });

  it('constructs each participating agent exactly once, sharing the instance between its Task and the Crew agents list', () => {
    const ir = multiAgentIR();
    const source = generateWorkflowFile('main', workflowFromFixture(ir, 'main'), ir);
    expect(source).toContain('intake_agent = build_intake_agent()');
    expect(source).toContain('research_specialist_agent = build_research_specialist_agent()');
    expect(source.match(/build_intake_agent\(\)/g)).toHaveLength(1);
    expect(source).toContain('agents=[intake_agent, research_specialist_agent]');
  });

  it('chains tasks via context=[previous_task] in declaration order', () => {
    const ir = multiAgentIR();
    const source = generateWorkflowFile('main', workflowFromFixture(ir, 'main'), ir);
    expect(source).toContain('task_intake = Task(');
    expect(source).toContain('task_research = Task(');
    expect(source).toContain('context=[task_intake]');
    expect(source).toContain('tasks=[task_intake, task_research]');
  });

  it("reuses each agent's own instructions as its task description", () => {
    const ir = multiAgentIR();
    const source = generateWorkflowFile('main', workflowFromFixture(ir, 'main'), ir);
    expect(source).toContain(
      'description="Triage the request and hand off to research when needed."',
    );
  });

  it('uses Process.sequential, never Process.hierarchical', () => {
    const ir = multiAgentIR();
    const source = generateWorkflowFile('main', workflowFromFixture(ir, 'main'), ir);
    expect(source).toContain('process=Process.sequential');
    expect(source).not.toContain('hierarchical');
  });

  it('produces syntactically valid Python', () => {
    const ir = multiAgentIR();
    const source = generateWorkflowFile('main', workflowFromFixture(ir, 'main'), ir);
    expect(isSyntacticallyValidPython(source)).toBe(true);
  });
});
