import { toIdentifier } from '@agentform/compiler';
import type { AgentformIR } from '@agentform/ir';
import { CREWAI_VERSION, PYTHON_VERSION_REQUIREMENT } from './versions.js';

/** A real, installable `pyproject.toml` — same verified `hatchling` + `packages = ["src"]` pattern as every other Python adapter in this repo. */
export function generatePyprojectToml(ir: AgentformIR): string {
  return [
    '[project]',
    `name = ${JSON.stringify(ir.application.name)}`,
    `version = ${JSON.stringify(ir.application.version)}`,
    `requires-python = ${JSON.stringify(PYTHON_VERSION_REQUIREMENT)}`,
    'dependencies = [',
    `    ${JSON.stringify(`crewai==${CREWAI_VERSION}`)},`,
    ']',
    '',
    '[build-system]',
    'requires = ["hatchling"]',
    'build-backend = "hatchling.build"',
    '',
    '[tool.hatch.build.targets.wheel]',
    'packages = ["src"]',
    '',
  ].join('\n');
}

/**
 * `OPENAI_API_KEY` and `GOOGLE_API_KEY`/`GEMINI_API_KEY` are named
 * explicitly — verified directly against the installed package's own
 * provider integrations (`crewai/llms/providers/openai/completion.py` and
 * `.../gemini/completion.py` both read these exact names via `os.getenv`).
 * Every other provider is free-form in Agentform's schema, so there's no
 * single fixed credential env var to name without guessing — documents the
 * declared models as a starting point instead.
 */
export function generateEnvExample(ir: AgentformIR): string {
  const lines = [
    '# CrewAI resolves each agent\'s llm= "<provider>/<model>" string against',
    'its own list of native provider integrations, falling back to LiteLLM',
    'when installed. The two natively-verified providers below read these',
    'exact environment variable names automatically:',
    '',
    '# For OpenAI models:',
  ];
  const modelLines = [...ir.models.entries()].map(
    ([id, model]) => `# ${id}: provider=${model.provider} model=${model.model}`,
  );
  return [
    ...lines.map((line) => (line.length > 0 ? `# ${line}` : '#')),
    'OPENAI_API_KEY=',
    '#',
    '# For Google/Gemini models (either name works):',
    'GOOGLE_API_KEY=',
    'GEMINI_API_KEY=',
    '#',
    '# Declared models in this application:',
    ...modelLines,
    '',
  ].join('\n');
}

export function generateReadme(ir: AgentformIR): string {
  return [
    `# ${ir.application.name} (CrewAI)`,
    '',
    'Generated by [Agentform](https://github.com/YASSERRMD/AgentForm) — do not edit the files under `src/` by hand; re-run `agentform compile --target crewai` instead.',
    '',
    '## Setup',
    '',
    '```bash',
    `python3 -m venv .venv && source .venv/bin/activate  # requires Python ${PYTHON_VERSION_REQUIREMENT}`,
    `pip install "crewai==${CREWAI_VERSION}"`,
    'cp .env.example .env   # then fill in your model provider credentials',
    '```',
    '',
    '## Run',
    '',
    '```bash',
    'python -m src.main',
    '```',
    '',
    '`pip install .` also works (see `pyproject.toml`) if you prefer an installed package over running from the project root.',
    '',
    '## Delegation',
    '',
    'Agents declared with `delegation.allowedAgents` get `allow_delegation=True`',
    "— CrewAI's own built-in delegate-to-coworker tool. **This is crew-wide,",
    'not scoped to specific coworkers**: any agent with delegation enabled can',
    'delegate to *every* other agent in its crew, not only the coworkers named',
    'in the specification. `agentform compile` reports this as a non-blocking',
    '`partial` compatibility entry rather than silently narrowing it — CrewAI',
    'has no mechanism to restrict which coworkers a given agent can reach.',
    '',
    '## Human input',
    '',
    'Not generated by this adapter. CrewAI has a real human-in-the-loop',
    'mechanism (`Task(human_input=True)`), but it is a *review-and-refine*',
    'loop scoped to one specific task ("hit Enter to accept, or type feedback',
    'to have the agent try again") rather than a graph-level approval gate —',
    'there is no reliable way to infer which generated task an Agentform',
    '`humanApproval` workflow node should attach to, so those nodes are',
    'reported as an unsupported/blocking diagnostic instead. If you need this,',
    'add `human_input=True` to the relevant `Task(...)` by hand in the',
    "generated workflow file — see CrewAI's human-in-the-loop docs.",
    '',
    '## Test',
    '',
    'This project has no generated tests — add your own and wire up a test runner of your choice (e.g. `pytest`).',
    '',
    '## Security',
    '',
    '- Tool bodies are generated as `NotImplementedError` stubs; nothing runs until you implement them.',
    '- No credentials are embedded in generated code — see `.env.example`.',
    '',
  ].join('\n');
}

interface WorkflowSummary {
  readonly id: string;
}

/** Runs the first declared workflow's crew — `Crew.kickoff()` is synchronous (verified: its real signature has no `async`), unlike `@agentform/adapter-autogen`/`@agentform/adapter-google-adk`'s `asyncio`-based entrypoints. */
export function generateMainFile(workflows: readonly WorkflowSummary[]): string {
  const [first] = workflows;
  if (first === undefined) {
    return [
      '"""No workflows are declared in this application."""',
      '',
      'def main() -> None:',
      '    raise NotImplementedError("No workflows are declared in this application.")',
      '',
      '',
      'if __name__ == "__main__":',
      '    main()',
      '',
    ].join('\n');
  }

  const moduleName = toIdentifier(first.id);
  return [
    `from .workflows.${moduleName} import build_crew`,
    '',
    '',
    'def main() -> None:',
    '    crew = build_crew()',
    '    result = crew.kickoff()',
    '    print(result.raw)',
    '',
    '',
    'if __name__ == "__main__":',
    '    main()',
    '',
  ].join('\n');
}
