import { toIdentifier } from '@agentform/compiler';
import type { AgentformIR } from '@agentform/ir';
import { AGNO_VERSION, FASTAPI_VERSION, PYTHON_VERSION_REQUIREMENT } from './versions.js';

/** A real, installable `pyproject.toml` — same verified `hatchling` + `packages = ["src"]` pattern as every other Python adapter in this repo. */
export function generatePyprojectToml(ir: AgentformIR): string {
  return [
    '[project]',
    `name = ${JSON.stringify(ir.application.name)}`,
    `version = ${JSON.stringify(ir.application.version)}`,
    `requires-python = ${JSON.stringify(PYTHON_VERSION_REQUIREMENT)}`,
    'dependencies = [',
    `    ${JSON.stringify(`agno==${AGNO_VERSION}`)},`,
    `    ${JSON.stringify(`fastapi==${FASTAPI_VERSION}`)},`,
    ']',
    '',
    '[build-system]',
    'requires = ["hatchling"]',
    'build-backend = "hatchling.build"',
    '',
    '[tool.hatch.build.targets.wheel]',
    'packages = ["src"]',
    '',
  ].join('\n');
}

/**
 * `OPENAI_API_KEY`/`ANTHROPIC_API_KEY`/`GOOGLE_API_KEY` are named
 * explicitly — verified directly against the installed package's own
 * model classes (`agno/models/{openai,anthropic,google}/*.py`, each reads
 * its own env var via `os.getenv`). Every other provider is free-form in
 * Agentform's schema, so there's no single fixed credential env var to
 * name without guessing — documents the declared models as a starting
 * point instead, matching every sibling Python adapter's `.env.example`.
 */
export function generateEnvExample(ir: AgentformIR): string {
  const modelLines = [...ir.models.entries()].map(
    ([id, model]) => `# ${id}: provider=${model.provider} model=${model.model}`,
  );
  return [
    '# agno.models.<provider> classes read these exact environment variable',
    '# names automatically (verified against the installed package):',
    '#',
    '# For OpenAI models:',
    'OPENAI_API_KEY=',
    '#',
    '# For Anthropic/Claude models:',
    'ANTHROPIC_API_KEY=',
    '#',
    '# For Google/Gemini models:',
    'GOOGLE_API_KEY=',
    '#',
    '# Declared models in this application:',
    ...modelLines,
    '',
  ].join('\n');
}

export function generateReadme(ir: AgentformIR): string {
  return [
    `# ${ir.application.name} (Agno)`,
    '',
    'Generated by [Agentform](https://github.com/YASSERRMD/AgentForm) — do not edit the files under `src/` by hand; re-run `agentform compile --target agno` instead.',
    '',
    '## Setup',
    '',
    '```bash',
    `python3 -m venv .venv && source .venv/bin/activate  # requires Python ${PYTHON_VERSION_REQUIREMENT}`,
    `pip install "agno==${AGNO_VERSION}" "fastapi==${FASTAPI_VERSION}"`,
    'cp .env.example .env   # then fill in your model provider credentials',
    '```',
    '',
    '`fastapi` is a direct dependency here, not just an Agno transitive one:',
    "`agno.workflow`'s own `__init__.py` unconditionally imports",
    '`agno.workflow.remote.RemoteWorkflow`, which needs `fastapi` — verified',
    'directly against the installed package (`import agno.workflow` raises',
    "`ModuleNotFoundError` without it), even though agno's own package",
    'metadata marks `fastapi` as belonging to an optional extra.',
    '',
    '## Run',
    '',
    '```bash',
    'python -m src.main',
    '```',
    '',
    '`pip install .` also works (see `pyproject.toml`) if you prefer an installed package over running from the project root.',
    '',
    '## Workflow structure',
    '',
    "Agentform's workflow model is a general graph (nodes and edges, with",
    "cycles allowed only through `loop` nodes); Agno's own model is",
    'fundamentally an ordered sequence of steps with structured nesting',
    '(`Loop`/`Parallel`/`Condition`/`Router`), not an arbitrary graph. Most',
    'node types translate directly and faithfully — see',
    "`docs/compiler-reference.md`'s compatibility matrix — but a few",
    'generated constructs are honest, documented stubs rather than complete',
    'translations:',
    '',
    '- **`loop` node bodies** are always a `NotImplementedError` stub. A',
    "  loop's back-edge creates a cycle Agentform's own graph model allows",
    '  but this adapter does not attempt to reconstruct into a real loop',
    "  body — the cycle's other nodes still get their own generated Steps",
    '  elsewhere in this file, but nothing wires them into the `Loop`',
    '  construct automatically.',
    '- **`router`/`condition` selector and evaluator functions** are',
    "  `NotImplementedError` stubs — Agentform's `expression`/`when` text has",
    '  no evaluator anywhere in this codebase by design (no `eval`, ever);',
    '  implement the real routing/condition logic by hand.',
    '- **A `tool` workflow node** (a tool called directly as a step, not by',
    "  an agent's own reasoning) generates a stub executor, since Agno's",
    '  tools are designed to be invoked by an agent, not run as standalone',
    '  workflow steps.',
    '',
    '## Human approval',
    '',
    '`humanApproval` workflow nodes generate `Step(requires_confirmation=',
    "True)` — Agno's own real, blocking human-in-the-loop gate (verified",
    'against the installed package), not an emulation. Tools with',
    '`sideEffect: destructive`, or declared as `type: humanApproval`,',
    'generate `@tool(requires_confirmation=True)` for the same reason at',
    'the tool level.',
    '',
    '## Test',
    '',
    'This project has no generated tests — add your own and wire up a test runner of your choice (e.g. `pytest`).',
    '',
    '## Security',
    '',
    '- Tool and stub step bodies are generated as `NotImplementedError` stubs; nothing runs until you implement them.',
    '- No credentials are embedded in generated code — see `.env.example`.',
    '',
  ].join('\n');
}

interface WorkflowSummary {
  readonly id: string;
}

/** Runs the first declared workflow — `Workflow.run()` is synchronous (verified: its real signature has no `async`), matching CrewAI's entrypoint style rather than AutoGen/Google ADK's `asyncio`-based one. */
export function generateMainFile(workflows: readonly WorkflowSummary[]): string {
  const [first] = workflows;
  if (first === undefined) {
    return [
      '"""No workflows are declared in this application."""',
      '',
      'def main() -> None:',
      '    raise NotImplementedError("No workflows are declared in this application.")',
      '',
      '',
      'if __name__ == "__main__":',
      '    main()',
      '',
    ].join('\n');
  }

  const moduleName = toIdentifier(first.id);
  return [
    `from .workflows.${moduleName} import build_${moduleName}_workflow`,
    '',
    '',
    'def main() -> None:',
    `    workflow = build_${moduleName}_workflow()`,
    '    result = workflow.run(input="")',
    '    print(result.content)',
    '',
    '',
    'if __name__ == "__main__":',
    '    main()',
    '',
  ].join('\n');
}
