import { describe, expect, it } from 'vitest';
import { generatedFileHeader, toIdentifier, toPascalCase } from './codegen-utils.js';

describe('toIdentifier', () => {
  it('replaces hyphens with underscores', () => {
    expect(toIdentifier('customer-support-agent')).toBe('customer_support_agent');
  });

  it('leaves an already-valid identifier untouched', () => {
    expect(toIdentifier('assistant')).toBe('assistant');
  });
});

describe('toPascalCase', () => {
  it('converts a hyphenated id to PascalCase', () => {
    expect(toPascalCase('customer-support-agent')).toBe('CustomerSupportAgent');
  });

  it('converts a single-word id', () => {
    expect(toPascalCase('assistant')).toBe('Assistant');
  });
});

describe('generatedFileHeader', () => {
  it('uses the given comment prefix', () => {
    const header = generatedFileHeader({ commentPrefix: '#' });
    expect(header).toContain('# Generated by Agentform');
  });

  it('includes source resource addresses when given', () => {
    const header = generatedFileHeader({
      commentPrefix: '//',
      sourceResourceAddresses: ['agent.intake', 'model.primary'],
    });
    expect(header).toContain('agent.intake, model.primary');
  });

  it('omits the source line when no addresses are given', () => {
    const header = generatedFileHeader({ commentPrefix: '//' });
    expect(header.split('\n')).toHaveLength(1);
  });

  it('never includes a timestamp', () => {
    const header = generatedFileHeader({ commentPrefix: '//' });
    expect(header).not.toMatch(/\d{4}-\d{2}-\d{2}/);
  });
});
