/**
 * Agentform identifiers allow hyphens (`^[a-zA-Z][a-zA-Z0-9_-]*$` —
 * `@agentform/schema`'s `identifierSchema`); TypeScript and Python
 * identifiers don't. This is the one normalization every adapter needs,
 * so it lives here rather than being reimplemented per adapter.
 */
export function toIdentifier(id: string): string {
  return id.replace(/-/g, '_');
}

/** `agent-intake` -> `AgentIntake` — for generated class/type names. */
export function toPascalCase(id: string): string {
  return toIdentifier(id)
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

export interface GeneratedFileHeaderOptions {
  readonly commentPrefix: string;
  readonly sourceResourceAddresses?: readonly string[];
}

/** A "generated by Agentform, do not edit" banner (§22 "include comments marking generated sections"), parameterized by the target language's line-comment syntax (`//` for TypeScript, `#` for Python). Deliberately carries no timestamp — see `manifest.ts`'s doc comment on why generated artifacts stay timestamp-free. */
export function generatedFileHeader(options: GeneratedFileHeaderOptions): string {
  const { commentPrefix: c } = options;
  const lines = [
    `${c} Generated by Agentform. Do not edit by hand — re-run \`agentform compile\` instead.`,
  ];
  if (options.sourceResourceAddresses && options.sourceResourceAddresses.length > 0) {
    lines.push(`${c} Source: ${options.sourceResourceAddresses.join(', ')}`);
  }
  return lines.join('\n');
}
