import type { AgentformIR } from '@agentform/ir';
import {
  NODE_ENGINE_RANGE,
  OPENAI_AGENTS_SDK_VERSION,
  TYPES_NODE_VERSION,
  TYPESCRIPT_VERSION,
  ZOD_VERSION,
} from './versions.js';

export function generatePackageJson(ir: AgentformIR): string {
  const packageJson = {
    name: `${ir.application.name}-openai`,
    version: ir.application.version,
    private: true,
    type: 'module',
    engines: { node: NODE_ENGINE_RANGE },
    scripts: {
      build: 'tsc',
      start: 'node dist/index.js',
    },
    dependencies: {
      '@openai/agents': OPENAI_AGENTS_SDK_VERSION,
      zod: ZOD_VERSION,
    },
    devDependencies: {
      typescript: TYPESCRIPT_VERSION,
      '@types/node': TYPES_NODE_VERSION,
    },
  };
  return `${JSON.stringify(packageJson, null, 2)}\n`;
}

export function generateTsconfig(): string {
  const tsconfig = {
    compilerOptions: {
      target: 'ES2022',
      module: 'NodeNext',
      moduleResolution: 'NodeNext',
      outDir: 'dist',
      rootDir: 'src',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      declaration: true,
    },
    include: ['src'],
  };
  return `${JSON.stringify(tsconfig, null, 2)}\n`;
}

/** Documents the env vars the OpenAI Agents SDK itself expects — never the resolved value of anything from the specification (§22 "avoid secret values, use environment-variable references"). `OPENAI_API_KEY` is what the SDK's own OpenAI client reads by default; nothing in generated code hardcodes it. */
export function generateEnvExample(): string {
  return ['# The OpenAI Agents SDK reads this automatically.', 'OPENAI_API_KEY=', ''].join('\n');
}

export function generateReadme(ir: AgentformIR): string {
  return [
    `# ${ir.application.name} (OpenAI Agents SDK)`,
    '',
    'Generated by [Agentform](https://github.com/YASSERRMD/AgentForm) — do not edit the files under `src/` by hand; re-run `agentform compile --target openai` instead.',
    '',
    '## Setup',
    '',
    '```bash',
    'npm install',
    'cp .env.example .env   # then fill in OPENAI_API_KEY',
    '```',
    '',
    '## Run',
    '',
    '```bash',
    'npm run build',
    'npm start',
    '```',
    '',
    '## Test',
    '',
    'This project has no generated tests — add your own under a `test/` directory and wire up a test runner of your choice.',
    '',
    '## Security',
    '',
    '- Tool `execute` functions are generated as throwing stubs; nothing runs until you implement them.',
    '- No credentials are embedded in generated code — see `.env.example`.',
    '',
  ].join('\n');
}

export function generateIndexFile(workflowFunctionNames: readonly string[]): string {
  if (workflowFunctionNames.length === 0) {
    return "export {};\n";
  }
  const [first] = workflowFunctionNames;
  return [
    `export * from './workflows/index.js';`,
    '',
    'async function main() {',
    `  const input = process.argv.slice(2).join(' ') || 'Hello!';`,
    `  const { ${first} } = await import('./workflows/index.js');`,
    `  const result = await ${first}(input);`,
    '  console.log(result.finalOutput);',
    '}',
    '',
    'if (import.meta.url === `file://${process.argv[1]}`) {',
    '  main();',
    '}',
    '',
  ].join('\n');
}

export function generateWorkflowsIndexFile(workflowIds: readonly string[]): string {
  const exports = workflowIds.map((id) => `export * from './${id}.js';`);
  return `${exports.join('\n')}\n`;
}

export function generateObservabilityStub(): string {
  return [
    '// The OpenAI Agents SDK has built-in tracing; no additional setup is generated here.',
    '// See https://platform.openai.com/docs for tracing dashboard configuration.',
    'export {};',
    '',
  ].join('\n');
}
