import { isSyntacticallyValidPython } from '@agentform/compiler';
import { describe, expect, it } from 'vitest';
import { generateWorkflowFile } from './generate-workflow.js';
import { baseIR, multiAgentIR } from './test-fixtures.js';

function workflowFromFixture(ir: ReturnType<typeof baseIR>, workflowId: string) {
  const workflow = ir.workflows.get(workflowId);
  if (!workflow) {
    throw new Error(`expected fixture to declare workflow "${workflowId}"`);
  }
  return workflow;
}

describe('generateWorkflowFile', () => {
  it('includes a generated-file header naming the source resource', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(baseIR(), 'main'));
    expect(source).toContain('# Generated by Agentform.');
    expect(source).toContain('# Source: workflow.main');
  });

  it("builds the entrypoint agent's factory function directly", () => {
    const source = generateWorkflowFile('main', workflowFromFixture(multiAgentIR(), 'main'));
    expect(source).toContain('from ..agents.intake import build_intake_agent');
    expect(source).toContain('def build_root_agent():');
    expect(source).toContain('return build_intake_agent()');
  });

  it('produces syntactically valid Python', () => {
    const source = generateWorkflowFile('main', workflowFromFixture(multiAgentIR(), 'main'));
    expect(isSyntacticallyValidPython(source)).toBe(true);
  });
});
