import { toIdentifier } from '@agentform/compiler';
import type { AgentformIR } from '@agentform/ir';
import { GOOGLE_ADK_VERSION, PYTHON_VERSION_REQUIREMENT } from './versions.js';

/** A real, installable `pyproject.toml` — same verified `hatchling` + `packages = ["src"]` pattern as `@agentform/adapter-langgraph`/`@agentform/adapter-autogen`. */
export function generatePyprojectToml(ir: AgentformIR): string {
  return [
    '[project]',
    `name = ${JSON.stringify(ir.application.name)}`,
    `version = ${JSON.stringify(ir.application.version)}`,
    `requires-python = ${JSON.stringify(PYTHON_VERSION_REQUIREMENT)}`,
    'dependencies = [',
    `    ${JSON.stringify(`google-adk==${GOOGLE_ADK_VERSION}`)},`,
    ']',
    '',
    '[build-system]',
    'requires = ["hatchling"]',
    'build-backend = "hatchling.build"',
    '',
    '[tool.hatch.build.targets.wheel]',
    'packages = ["src"]',
    '',
  ].join('\n');
}

/** Same reasoning as every other Python adapter: `model.provider` is free-form, so there's no single fixed credential env var to name without guessing — documents declared models instead. ADK's own Gemini path reads `GOOGLE_API_KEY`/`GOOGLE_GENAI_USE_VERTEXAI` by convention, called out explicitly since it's the one credential this adapter's own model-string generation can name with confidence. */
export function generateEnvExample(ir: AgentformIR): string {
  const lines = [
    '# For Google/Gemini models (the ADK SDK reads this automatically):',
    'GOOGLE_API_KEY=',
    '#',
    '# Non-Gemini providers need a real BaseLlm instance instead of a plain',
    "# model string — see the TODO comment in that agent's generated file, and",
    '# set whichever credential env var that provider expects here.',
  ];
  const modelLines = [...ir.models.entries()].map(
    ([id, model]) => `# ${id}: provider=${model.provider} model=${model.model}`,
  );
  return [...lines, '#', ...modelLines, ''].join('\n');
}

export function generateReadme(ir: AgentformIR): string {
  return [
    `# ${ir.application.name} (Google Agent Development Kit)`,
    '',
    'Generated by [Agentform](https://github.com/YASSERRMD/AgentForm) — do not edit the files under `src/` by hand; re-run `agentform compile --target google-adk` instead.',
    '',
    '## Setup',
    '',
    '```bash',
    `python3 -m venv .venv && source .venv/bin/activate  # requires Python ${PYTHON_VERSION_REQUIREMENT}`,
    `pip install "google-adk==${GOOGLE_ADK_VERSION}"`,
    'cp .env.example .env   # then fill in your model provider credentials',
    '```',
    '',
    '## Run',
    '',
    '```bash',
    'python -m src.main',
    '```',
    '',
    '`pip install .` also works (see `pyproject.toml`) if you prefer an installed package over running from the project root.',
    '',
    '## Delegation',
    '',
    'Agents declared with `delegation.allowedAgents` become ADK `sub_agents` —',
    "ADK's own built-in transfer mechanism, not something this adapter",
    'implements itself. **ADK requires a single-parent tree**: if two different',
    'agents in your specification name the same delegate, `agentform compile`',
    'reports it as an unsupported/blocking diagnostic rather than generating',
    'code that would fail at import time.',
    '',
    '## Human approval',
    '',
    'ADK has a real, native tool-level confirmation mechanism',
    '(`FunctionTool(func, require_confirmation=True)`) but no workflow-node-level',
    'equivalent — `humanApproval` workflow nodes are reported unsupported by',
    'this adapter rather than emulated. If you need approval gating, wrap the',
    'specific tool call that needs it with `require_confirmation=True` by hand',
    "in the generated tool file — see ADK's tool confirmation docs.",
    '',
    '## Test',
    '',
    'This project has no generated tests — add your own and wire up a test runner of your choice (e.g. `pytest`).',
    '',
    '## Security',
    '',
    '- Tool bodies are generated as `NotImplementedError` stubs; nothing runs until you implement them.',
    '- No credentials are embedded in generated code — see `.env.example`.',
    '',
  ].join('\n');
}

interface WorkflowSummary {
  readonly id: string;
}

/** Runs the first declared workflow's root agent through a real `Runner` + `InMemorySessionService` — verified end-to-end against the installed package, including the exact async `create_session`/`run_async`/event-streaming shape. */
export function generateMainFile(workflows: readonly WorkflowSummary[]): string {
  const [first] = workflows;
  if (first === undefined) {
    return [
      '"""No workflows are declared in this application."""',
      '',
      'def main() -> None:',
      '    raise NotImplementedError("No workflows are declared in this application.")',
      '',
      '',
      'if __name__ == "__main__":',
      '    main()',
      '',
    ].join('\n');
  }

  const moduleName = toIdentifier(first.id);
  return [
    'import asyncio',
    '',
    'from google.adk.runners import Runner',
    'from google.adk.sessions import InMemorySessionService',
    'from google.genai import types',
    '',
    `from .workflows.${moduleName} import build_root_agent`,
    '',
    'APP_NAME = "agentform-app"',
    '',
    '',
    'async def main() -> None:',
    '    session_service = InMemorySessionService()',
    '    session = await session_service.create_session(app_name=APP_NAME, user_id="user")',
    '    runner = Runner(app_name=APP_NAME, agent=build_root_agent(), session_service=session_service)',
    '',
    '    message = types.Content(role="user", parts=[types.Part.from_text(text="Hello!")])',
    '    async for event in runner.run_async(user_id="user", session_id=session.id, new_message=message):',
    '        if event.is_final_response() and event.content and event.content.parts:',
    '            for part in event.content.parts:',
    '                if part.text:',
    '                    print(part.text)',
    '',
    '',
    'if __name__ == "__main__":',
    '    asyncio.run(main())',
    '',
  ].join('\n');
}
